//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyMaker.UI.Light.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\TexasHoldem\\888Poker\\HandsHistory\\Cash")]
        public string HandHistoryFolder {
            get {
                return ((string)(this["HandHistoryFolder"]));
            }
            set {
                this["HandHistoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\TexasHoldem\\888Poker\\HandsHistory\\VipNeborak")]
        public string FileTrackingFolder {
            get {
                return ((string)(this["FileTrackingFolder"]));
            }
            set {
                this["FileTrackingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VipNeborak")]
        public string Hero {
            get {
                return ((string)(this["Hero"]));
            }
            set {
                this["Hero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal CommitCount {
            get {
                return ((decimal)(this["CommitCount"]));
            }
            set {
                this["CommitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsManualInitializing {
            get {
                return ((bool)(this["IsManualInitializing"]));
            }
            set {
                this["IsManualInitializing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_Hands {
            get {
                return ((bool)(this["Stat_Hands"]));
            }
            set {
                this["Stat_Hands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_PFR {
            get {
                return ((bool)(this["Stat_PFR"]));
            }
            set {
                this["Stat_PFR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_VPIP {
            get {
                return ((bool)(this["Stat_VPIP"]));
            }
            set {
                this["Stat_VPIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_Win {
            get {
                return ((bool)(this["Stat_Win"]));
            }
            set {
                this["Stat_Win"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_Profit {
            get {
                return ((bool)(this["Stat_Profit"]));
            }
            set {
                this["Stat_Profit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_ATS {
            get {
                return ((bool)(this["Stat_ATS"]));
            }
            set {
                this["Stat_ATS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_AF {
            get {
                return ((bool)(this["Stat_AF"]));
            }
            set {
                this["Stat_AF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_3B {
            get {
                return ((bool)(this["Stat_3B"]));
            }
            set {
                this["Stat_3B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_BB {
            get {
                return ((bool)(this["Stat_BB"]));
            }
            set {
                this["Stat_BB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_EP_PFR {
            get {
                return ((bool)(this["Stat_EP_PFR"]));
            }
            set {
                this["Stat_EP_PFR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_MP_PFR {
            get {
                return ((bool)(this["Stat_MP_PFR"]));
            }
            set {
                this["Stat_MP_PFR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_LP_PFR {
            get {
                return ((bool)(this["Stat_LP_PFR"]));
            }
            set {
                this["Stat_LP_PFR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_EP_VPIP {
            get {
                return ((bool)(this["Stat_EP_VPIP"]));
            }
            set {
                this["Stat_EP_VPIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_MP_VPIP {
            get {
                return ((bool)(this["Stat_MP_VPIP"]));
            }
            set {
                this["Stat_MP_VPIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_LP_VPIP {
            get {
                return ((bool)(this["Stat_LP_VPIP"]));
            }
            set {
                this["Stat_LP_VPIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_AF_Flop {
            get {
                return ((bool)(this["Stat_AF_Flop"]));
            }
            set {
                this["Stat_AF_Flop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_AF_Turn {
            get {
                return ((bool)(this["Stat_AF_Turn"]));
            }
            set {
                this["Stat_AF_Turn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_AF_River {
            get {
                return ((bool)(this["Stat_AF_River"]));
            }
            set {
                this["Stat_AF_River"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_ATS_CO {
            get {
                return ((bool)(this["Stat_ATS_CO"]));
            }
            set {
                this["Stat_ATS_CO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_ATS_B {
            get {
                return ((bool)(this["Stat_ATS_B"]));
            }
            set {
                this["Stat_ATS_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_ATS_SB {
            get {
                return ((bool)(this["Stat_ATS_SB"]));
            }
            set {
                this["Stat_ATS_SB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int LiveGamesCount {
            get {
                return ((int)(this["LiveGamesCount"]));
            }
            set {
                this["LiveGamesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_Fold_SB_ToSteal {
            get {
                return ((bool)(this["Stat_Fold_SB_ToSteal"]));
            }
            set {
                this["Stat_Fold_SB_ToSteal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Stat_Fold_BB_ToSteal {
            get {
                return ((bool)(this["Stat_Fold_BB_ToSteal"]));
            }
            set {
                this["Stat_Fold_BB_ToSteal"] = value;
            }
        }
    }
}
